# Generated by Django 3.2.20 on 2025-05-28 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('purpose', models.CharField(choices=[('subscription_setup', 'Subscription Setup'), ('one_time_payment', 'One-time Payment'), ('trial_extension', 'Trial Extension')], max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='created', max_length=30)),
                ('paypal_response_data', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_intents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_payment_id', models.CharField(max_length=255, unique=True)),
                ('paypal_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('payment_type', models.CharField(choices=[('subscription', 'Subscription Payment'), ('one_time', 'One-time Payment')], default='subscription', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('paypal_response_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paypal_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayPalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_plan_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('inactive', 'Inactive'), ('active', 'Active')], default='created', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('interval_unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=10)),
                ('interval_count', models.IntegerField(default=1)),
                ('paypal_response_data', models.JSONField(default=dict)),
                ('total_subscriptions', models.IntegerField(default=0)),
                ('active_subscriptions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paypal_plans',
            },
        ),
        migrations.CreateModel(
            name='PayPalSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_subscription_id', models.CharField(max_length=255, unique=True)),
                ('paypal_plan_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('approval_pending', 'Approval Pending'), ('approved', 'Approved'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='approval_pending', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('next_billing_time', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=2.0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('approval_url', models.URLField(blank=True, null=True)),
                ('paypal_response_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paypal_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PayPalWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('event_data', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('processing_attempts', models.IntegerField(default=0)),
                ('last_processing_attempt', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paypalpayment')),
                ('related_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paypalsubscription')),
            ],
            options={
                'db_table': 'paypal_webhook_events',
                'ordering': ['-received_at'],
            },
        ),
    ]
