# Generated by Django 3.2.20 on 2025-05-28 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='githubissue',
            name='github_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.githubinfo'),
        ),
        migrations.AddField(
            model_name='githubinfo',
            name='scan_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_info', to='projects.scandata'),
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='github_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='projects.githubinfo'),
        ),
        migrations.AddField(
            model_name='conversionresult',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_result', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='githubissue',
            unique_together={('github_info', 'github_issue_id')},
        ),
    ]
